spring:
  application:
    name: userService
  cloud:
    config:
      server:
        git:
          uri: https://github.com/q1219331697/spring-cloud-demo-config-repo
        encrypt:
          enabled: false

server:
  port: 0
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/